
package minijira.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "minijiraWS", targetNamespace = "http://ws.minijira/", wsdlLocation = "http://localhost:8080/minijiraWS/dbCRUD?wsdl")
public class MinijiraWS
    extends Service
{

    private final static URL MINIJIRAWS_WSDL_LOCATION;
    private final static WebServiceException MINIJIRAWS_EXCEPTION;
    private final static QName MINIJIRAWS_QNAME = new QName("http://ws.minijira/", "minijiraWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/minijiraWS/dbCRUD?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MINIJIRAWS_WSDL_LOCATION = url;
        MINIJIRAWS_EXCEPTION = e;
    }

    public MinijiraWS() {
        super(__getWsdlLocation(), MINIJIRAWS_QNAME);
    }

    public MinijiraWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), MINIJIRAWS_QNAME, features);
    }

    public MinijiraWS(URL wsdlLocation) {
        super(wsdlLocation, MINIJIRAWS_QNAME);
    }

    public MinijiraWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MINIJIRAWS_QNAME, features);
    }

    public MinijiraWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MinijiraWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DbCRUD
     */
    @WebEndpoint(name = "dbCRUDPort")
    public DbCRUD getDbCRUDPort() {
        return super.getPort(new QName("http://ws.minijira/", "dbCRUDPort"), DbCRUD.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DbCRUD
     */
    @WebEndpoint(name = "dbCRUDPort")
    public DbCRUD getDbCRUDPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.minijira/", "dbCRUDPort"), DbCRUD.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MINIJIRAWS_EXCEPTION!= null) {
            throw MINIJIRAWS_EXCEPTION;
        }
        return MINIJIRAWS_WSDL_LOCATION;
    }

}
