
package minijira.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "minijiraWS", targetNamespace = "http://ws.minijira/", wsdlLocation = "http://localhost:8080/minijiraWS/dbCRUD?wsdl")
public class MinijiraWS
    extends Service
{

    private final static URL MINIJIRAWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(minijira.ws.MinijiraWS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = minijira.ws.MinijiraWS.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/minijiraWS/dbCRUD?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/minijiraWS/dbCRUD?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MINIJIRAWS_WSDL_LOCATION = url;
    }

    public MinijiraWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MinijiraWS() {
        super(MINIJIRAWS_WSDL_LOCATION, new QName("http://ws.minijira/", "minijiraWS"));
    }

    /**
     * 
     * @return
     *     returns DbCRUD
     */
    @WebEndpoint(name = "dbCRUDPort")
    public DbCRUD getDbCRUDPort() {
        return super.getPort(new QName("http://ws.minijira/", "dbCRUDPort"), DbCRUD.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DbCRUD
     */
    @WebEndpoint(name = "dbCRUDPort")
    public DbCRUD getDbCRUDPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.minijira/", "dbCRUDPort"), DbCRUD.class, features);
    }

}
