
package minijira.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "dbCRUD", targetNamespace = "http://ws.minijira/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DbCRUD {


    /**
     * 
     * @return
     *     returns java.util.List<minijira.ws.Tech>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTechsList", targetNamespace = "http://ws.minijira/", className = "minijira.ws.GetTechsList")
    @ResponseWrapper(localName = "getTechsListResponse", targetNamespace = "http://ws.minijira/", className = "minijira.ws.GetTechsListResponse")
    public List<Tech> getTechsList();

    /**
     * 
     * @param guestName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.minijira/", className = "minijira.ws.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.minijira/", className = "minijira.ws.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "guestName", targetNamespace = "")
        String guestName);

    /**
     * 
     * @return
     *     returns minijira.ws.Tech
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFirstTech", targetNamespace = "http://ws.minijira/", className = "minijira.ws.GetFirstTech")
    @ResponseWrapper(localName = "getFirstTechResponse", targetNamespace = "http://ws.minijira/", className = "minijira.ws.GetFirstTechResponse")
    public Tech getFirstTech();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeTech", targetNamespace = "http://ws.minijira/", className = "minijira.ws.RemoveTech")
    @ResponseWrapper(localName = "removeTechResponse", targetNamespace = "http://ws.minijira/", className = "minijira.ws.RemoveTechResponse")
    public void removeTech(
        @WebParam(name = "arg0", targetNamespace = "")
        Tech arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "mergeTech", targetNamespace = "http://ws.minijira/", className = "minijira.ws.MergeTech")
    @ResponseWrapper(localName = "mergeTechResponse", targetNamespace = "http://ws.minijira/", className = "minijira.ws.MergeTechResponse")
    public void mergeTech(
        @WebParam(name = "arg0", targetNamespace = "")
        Tech arg0);

}
